# Generated by Django 4.0.2 on 2022-02-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_musicschedule_music_url_alter_musicschedule_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicschedule',
            name='is_repeat',
            field=models.BooleanField(default=True),
        ),
    ]
