# Generated by Django 4.0.2 on 2022-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_musicschedule_is_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicschedule',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musicschedule',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='./music'),
        ),
    ]
